# Generated by Django 4.2.6 on 2023-11-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Critical"),
                            (1, "Error"),
                            (2, "Warning"),
                            (3, "Debug"),
                            (4, "Info"),
                        ]
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
