# Generated by Django 4.2.6 on 2023-10-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TelegramChannel",
            new_name="Channel",
        ),
        migrations.RenameModel(
            old_name="TelegramMessage",
            new_name="Message",
        ),
    ]
