# Generated by Django 4.2.6 on 2023-10-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0002_rename_telegramchannel_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="channel_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
