# Generated by Django 4.2.6 on 2023-10-15 16:56

from django.db import migrations
import sources.models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0003_channel_channel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="embedding",
            field=sources.models.EmbeddingField(blank=True, null=True),
        ),
    ]
